### ISSUE TITLE
puppetlabs-stdlib 6.*.* support?

### ISSUE THREAD

**Issue by matthiasbeyer** [bodgit/puppet-sssd#22]
Please update to support stdlib 6.*.*!

**Comment by matthiasbeyer** [comment]
Thanks for updating this. Unfortunately:

```
$ puppet module install bodgit-sssd
[...]
Error: Could not install module 'bodgit-sssd' (v3.0.0)
  The requested version cannot satisfy one or more of the following installed modules:
    puppetlabs-stdlib, installed: 6.6.0, expected: >=4.25.0 <8.0.0

  Use `puppet module install 'bodgit-sssd' --ignore-dependencies` to install only this module
```

I din't know what is happening... Maybe you know something?

**Comment by bodgit** [comment]
I thought I'd made a typo in the version requirement, but I _think_ the error is actually coming from my dbus module which still has a similar old stdlib dependency that I just need to update. I've got one other module to fix up first then I'll sort that one out.

At least don't think it's a problem with this sssd module. You can probably use `--ignore-dependencies` and it'll be fine for now.

Sometimes `puppet module install ...` doesn't give the clearest error messages.

**Comment by bodgit** [comment]
I've just pushed v3.0.1 to the forge which has no real changes apart from an updated dependency for dbus, which itself has been updated for the newer stdlib versions so you shouldn't get this error now.
