### ISSUE TITLE
transfer to voxpupuli?

### ISSUE THREAD

**Issue by jhoblitt** [bodgit/puppet-sssd#38]
@bodgit I believe it has been over a year since a commit has been made to this repo.  Would you consider transferring the module to voxpupuli?

**Comment by teluq-pbrideau** [comment]
Can I do something to help this issue move forward?  I’m just a user of this module (my contribution (#34) is still not yet merged) , but would like also to see its stdlib dependency updated to the new version (9.x)

**Comment by bastelfreak** [comment]
Vox Pupuli has now it's own module: https://forge.puppet.com/modules/puppet/sssd/readme

**Comment by jhoblitt** [comment]
I'm closing this request as I'm planning to migrate to the vox pupili module.
