### ISSUE TITLE
noop not working on sssd::domain as expected

### ISSUE THREAD

**Issue by davidvanlaatum** [bodgit/puppet-sssd#9]
```
sssd::domain {
        'example.com':
          noop                           => true,
          dyndns_update                  => true,
....
```
actual output
```
Notice: /Stage[main]/Base/Sssd::Domain[example.com]/Sssd_conf[domain/example.com/dyndns_update]/ensure: created
```
expected output
```
Notice: /Stage[main]/Base/Sssd::Domain[example.com]/Sssd_conf[domain/example.com/dyndns_update]/ensure: current_value 'absent', should be 'present' (noop)
```

**Comment by bodgit** [comment]
I don't think this is supposed to work. See https://projects.puppetlabs.com/issues/7793.

If you run `puppet agent --noop ...` then that should work as it's inherited by all resources and correctly show what would be applied, albeit at a global level.

**Comment by davidvanlaatum** [comment]
providers are supposed to provide an option to only report on the changes sssd::domain is a provider not a class. 
Right now classes do not behave like resources and we do not want to work towards that end
sssd::domain is a resource so should behave like one and honour the noop flag

**Comment by davidvanlaatum** [comment]
Im actually kinda surprised this doesn't work by default
